
getTestTeams = function () {
    return [
        {
            "parent_team__id": "test",
            "is_hidden": "",
            "status": "active",
            "name": "Test Team 1",
            "company_name": "test",
            "parent_team__name": "test",
            "company__reference": "123",
            "parent_team__reference": "123",
            "reference": "1234",
            "id": "test"
        },
        {
            "parent_team__id": "test2",
            "is_hidden": "",
            "status": "active",
            "name": "Test Team 2",
            "company_name": "test2",
            "parent_team__name": "test2",
            "company__reference": "234",
            "parent_team__reference": "234",
            "reference": "2345",
            "id": "test2"
        }
    ]
}

getTestJobs = function () {
    return [
        {
            "visibility": "invite-only",
            "status": "open",
            "public_url": "https://www.odesk.com/jobs/~01287e314daf4e286a",
            "budget": "20",
            "reference": "202557357",
            "num_candidates": "1",
            "start_date": "1368921600000",
            "num_new_candidates": "1",
            "filled_date": "",
            "category": "Web Development",
            "attachment_file_url": "",
            "off_the_network": "",
            "buyer_company__reference": "118",
            "buyer_team__reference": "416616",
            "num_active_candidates": "1",
            "created_time": "1369022107000",
            "last_candidacy_access_time": "",
            "duration": "",
            "created_by_name": "Greg Little",
            "description": "test job 1\n\n(task id: Zsr6sJLPuh)",
            "buyer_company__name": "oDesk",
            "subcategory": "Web Programming",
            "job_type": "fixed-price",
            "buyer_team__name": "oDesk R&D BootCamp",
            "buyer_team__id": "odesk:rndbootcamp",
            "end_date": "1369526400000",
            "title": "test job 1",
            "cancelled_date": "",
            "created_by": "greglittle",
            "count_total_applicants": "1",
            "count_new_applicants": "1",
            "count_total_candidates": "1"
        },
        {
            "visibility": "invite-only",
            "status": "open",
            "public_url": "https://www.odesk.com/jobs/~01287e314daf4e286a",
            "budget": "20",
            "reference": "202557356",
            "num_candidates": "0",
            "start_date": "1368921600000",
            "num_new_candidates": "0",
            "filled_date": "",
            "category": "Web Development",
            "attachment_file_url": "",
            "off_the_network": "",
            "buyer_company__reference": "118",
            "buyer_team__reference": "416616",
            "num_active_candidates": "0",
            "created_time": "1369022107000",
            "last_candidacy_access_time": "",
            "duration": "",
            "created_by_name": "Greg Little",
            "description": "test job 2\n\n(task id: Zsr6sJLPuh)",
            "buyer_company__name": "oDesk",
            "subcategory": "Web Programming",
            "job_type": "fixed-price",
            "buyer_team__name": "oDesk R&D BootCamp",
            "buyer_team__id": "odesk:rndbootcamp",
            "end_date": "1369526400000",
            "title": "test job 2",
            "cancelled_date": "",
            "created_by": "greglittle",
            "count_total_applicants": "0",
            "count_new_applicants": "0",
            "count_total_candidates": "0"
        }
    ]
}

function getTestEngs() {
    return [
        {
            "rent_percent": "10",
            "estimated_duration_id": "5",
            "provider__id": "testuser1",
            "fixed_price_upfront_payment": "0",
            "modified_time": "1365413598000",
            "job__reference": "202383623",
            "estimated_duration": "Less than 1 week",
            "roles": {
                "role": "buyer"
            },
            "weekly_limit_next_week": "",
            "offer__reference": "237286567",
            "buyer_team__reference": "416616",
            "engagement_end_date": "",
            "created_time": "1365413598000",
            "description": "",
            "provider_team__reference": "",
            "engagement_start_date": "1365379200000",
            "buyer_team__id": "odesk:rndbootcamp",
            "provider_team__id": "",
            "status": "active",
            "engagement_title": "test job A",
            "provider__reference": "1977857",
            "fixed_pay_amount_agreed": "30.00",
            "reference": "12967056",
            "fixed_charge_amount_agreed": "33.33",
            "engagement_job_type": "fixed-price",
            "job__title": "test job A",
            "provider__has_agency": ""
        },
        {
            "rent_percent": "10",
            "estimated_duration_id": "5",
            "provider__id": "testuser2",
            "fixed_price_upfront_payment": "0",
            "modified_time": "1365413598000",
            "job__reference": "202383623",
            "estimated_duration": "Less than 1 week",
            "roles": {
                "role": "buyer"
            },
            "weekly_limit_next_week": "",
            "offer__reference": "237286567",
            "buyer_team__reference": "416616",
            "engagement_end_date": "",
            "created_time": "1365413598000",
            "description": "",
            "provider_team__reference": "",
            "engagement_start_date": "1365379200000",
            "buyer_team__id": "odesk:rndbootcamp",
            "provider_team__id": "",
            "status": "active",
            "engagement_title": "test job B",
            "provider__reference": "1977857",
            "fixed_pay_amount_agreed": "30.00",
            "reference": "12967056",
            "fixed_charge_amount_agreed": "33.33",
            "engagement_job_type": "fixed-price",
            "job__title": "test job B",
            "provider__has_agency": ""
        }
    ]
}

function getTestApps() {
    return [
        {
            "estimated_duration_id": "5",
            "staffer_user__name": "Test User X",
            "created_type": "provider",
            "fixed_price_upfront_payment": "20",
            "modified_time": "1369120085000",
            "key": "~~5f881beee10f7943",
            "job__reference": "202562421",
            "has_buyer_signed": "",
            "is_hidden": "",
            "buyer_company__reference": "118",
            "engagement_end_date": "",
            "is_matching_preferences": "1",
            "created_time": "1369120085000",
            "description": "",
            "buyer_company__name": "oDesk",
            "my_role": "buyer",
            "engagement_start_date": "1369008000000",
            "buyer_team__id": "odesk:rndbootcamp",
            "buyer_user__id": "",
            "created_by": "testuserx",
            "provider_team__id": "testuserx",
            "has_provider_signed": "1",
            "provider_team__name": "Test User Solutions",
            "staffer_user__id": "testuserx",
            "provider__feedback_score": "0",
            "fixed_pay_amount_agreed": "100",
            "fixed_charge_amount_agreed": "111.11",
            "candidacy_status": "in_process",
            "staffer_user__reference": "1719674",
            "is_viewed": "",
            "message_from_provider": "Hello, this is my cover letter, which is a test cover letter for testing purposes, so we have something to show here.",
            "engagement_job_type": "fixed-price",
            "reason_code": "",
            "signed_by_buyer_user": "",
            "interview_status": "waiting_for_buyer",
            "buyer_team__name": "oDesk > oDesk R&D BootCamp",
            "provider__has_agency": "1",
            "rent_percent": "10",
            "provider__id": "testuserx",
            "reason_reference": "",
            "is_shortlisted": "",
            "estimated_duration": "Less than 1 week",
            "hiring_time": "",
            "roles": {
                "role": "buyer"
            },
            "signed_time_buyer": "",
            "attachment_file_url": "",
            "buyer_team__reference": "416616",
            "attachment_by": "",
            "buyer_user__name": "",
            "signed_by_provider_user": "testuserx",
            "provider_team__reference": "415879",
            "engagement__reference": "",
            "job__description": "task: https://github.com/dglittle/password-generator/issues/1\n\nsubmit result as pull request\n\nI'll hire the first person that answers these questions correctly in their cover letter:\n\n1. what is your github id?\n2. how long will this task take you?\n3. how would you convert an 8-bit hex number like \"f3\" into an integer?\n\n\n(task id: 4qLZAq23zw)",
            "provider_company__reference": "415879",
            "signed_time_provider": "1369120085000",
            "provider__name": "Test User X",
            "provider__total_hours": "",
            "provider__profile_url": "https://www.odesk.com/users/~0181d7da6c3671ac21",
            "status": "",
            "engagement_title": "",
            "message_from_buyer": "",
            "provider_company__name": "Test User Solutions",
            "provider__reference": "12345",
            "buyer_last_offer_user__id": "",
            "info_matching_preferences": {
                "prefs_total": "1",
                "prefs_match": "1",
                "match_details": {
                    "candidate_type_pref": {
                        "Value": "all",
                        "Match": "yes"
                    }
                }
            },
            "reference": "1234567",
            "reason_extra": "",
            "expiration_date": "",
            "job__title": "Add enhancement in open source javascript project: password-generator",
            "reason_inactive": "",
            "buyer_user__reference": "",
            "is_undecided": "1"
        },
        {
            "estimated_duration_id": "5",
            "staffer_user__name": "Test User Y",
            "created_type": "provider",
            "fixed_price_upfront_payment": "0",
            "modified_time": "1369120085000",
            "key": "~~5f881beee10f7943",
            "job__reference": "202562421",
            "has_buyer_signed": "",
            "is_hidden": "",
            "buyer_company__reference": "118",
            "engagement_end_date": "",
            "is_matching_preferences": "1",
            "created_time": "1369120085000",
            "description": "",
            "buyer_company__name": "oDesk",
            "my_role": "buyer",
            "engagement_start_date": "1369008000000",
            "buyer_team__id": "odesk:rndbootcamp",
            "buyer_user__id": "",
            "created_by": "testusery",
            "provider_team__id": "testusery",
            "has_provider_signed": "1",
            "provider_team__name": "Test User Solutions",
            "staffer_user__id": "testusery",
            "provider__feedback_score": "0",
            "fixed_pay_amount_agreed": "100",
            "fixed_charge_amount_agreed": "111.11",
            "candidacy_status": "in_process",
            "staffer_user__reference": "1719674",
            "is_viewed": "",
            "message_from_provider": "Hello, this is my cover letter, which is a test cover letter for testing purposes, so we have something to show here.",
            "engagement_job_type": "fixed-price",
            "reason_code": "",
            "signed_by_buyer_user": "",
            "interview_status": "waiting_for_buyer",
            "buyer_team__name": "oDesk > oDesk R&D BootCamp",
            "provider__has_agency": "1",
            "rent_percent": "10",
            "provider__id": "testusery",
            "reason_reference": "",
            "is_shortlisted": "",
            "estimated_duration": "Less than 1 week",
            "hiring_time": "",
            "roles": {
                "role": "buyer"
            },
            "signed_time_buyer": "",
            "attachment_file_url": "",
            "buyer_team__reference": "416616",
            "attachment_by": "",
            "buyer_user__name": "",
            "signed_by_provider_user": "testuserx",
            "provider_team__reference": "415879",
            "engagement__reference": "",
            "job__description": "task: https://github.com/dglittle/password-generator/issues/1\n\nsubmit result as pull request\n\nI'll hire the first person that answers these questions correctly in their cover letter:\n\n1. what is your github id?\n2. how long will this task take you?\n3. how would you convert an 8-bit hex number like \"f3\" into an integer?\n\n\n(task id: 4qLZAq23zw)",
            "provider_company__reference": "415879",
            "signed_time_provider": "1369120085000",
            "provider__name": "Test User Y",
            "provider__total_hours": "",
            "provider__profile_url": "https://www.odesk.com/users/~0181d7da6c3671ac21",
            "status": "",
            "engagement_title": "",
            "message_from_buyer": "",
            "provider_company__name": "Test User Solutions",
            "provider__reference": "12345",
            "buyer_last_offer_user__id": "",
            "info_matching_preferences": {
                "prefs_total": "1",
                "prefs_match": "1",
                "match_details": {
                    "candidate_type_pref": {
                        "Value": "all",
                        "Match": "yes"
                    }
                }
            },
            "reference": "1234567",
            "reason_extra": "",
            "expiration_date": "",
            "job__title": "Add enhancement in open source javascript project: password-generator",
            "reason_inactive": "",
            "buyer_user__reference": "",
            "is_undecided": "1"
        }
    ]
}
